export default [
    {
        id: '0',
        name: 'Dr Kalpana Nagpal',
        image: require('../../../assets/images/kalpana.jpeg'),
        speciality: 'ENT',
        fee: '500',
        qualification: 'MBBS, MS (ENT), DNB (ENT)',
        coordinate: {
            latitude: 28.5672,
            longitude: 28.5672,
        },
        description: 'Offered treatments in Robotic Surgery for snoring problem – snoring & Sleep Apnea Robotic Scarless Thyroid Surgery',
        experience: '5',
        language: 'English/Hindi',
    },
    {
        id: '1',
        name: 'Dr. Avtar Singh Bath',
        image: require('../../../assets/images/avtar.jpeg'),
        speciality: 'Plastic & Cosmetic Surgery',
        fee: '700',
        qualification: 'MBBS MS (General Surgery) M Ch (Plastic Surgery)',
        coordinate: {
            latitude: 30.0818,
            longitude: 78.2888,
        },
        description: 'With over 33 years of experience in Plastic and Cosmetic Surgery, Dr. (Maj Gen) Avtar Singh Bath is a Plastic Surgeon of repute and distinct pioneer in many fields of Plastic Surgery.  He is the first in the country to start calvarial bone grafting procedures, comprehensive management of arteriovenous malformations, new modalities of treatment of tendon injuries of the hand, management of pectus excavatum and separation of conjoint twins. He is a pioneer in use of autologus therapies (Fat Grafting, P.R.P. therapy) in cosmetic surgery. Some of his original work has been highlighted in Discovery channel and other T.V. channels of repute. His speciality interest is in Cosmetic Surgery, General Plastic Surgery, Micro Surgery, Brachial Plexus surgery and Hand Surgery. He played a significant role in setting up state of art Plastic and Cosmetic Surgery Centre at Army Hospital (R&R) Delhi Cantt and BLK Super Speciality Hospital New Delhi. He has been a teacher and examiner of M.Ch and D.N.B. Plastic Surgery in many prestigious universities and he has more than 30 publications in national and international journals.',
        experience: '33',
        language: 'English',
    },
    {
        id: '2',
        name: 'Dr Ishwar Bohra',
        image: require('../../../assets/images/ishwar.jpeg'),
        speciality: 'Orthopaedics',
        fee: '600',
        qualification: 'MBBS, M.Ch. (Ortho), MS (Ortho) and MAMS',
        coordinate: {
            latitude: 21.2574,
            longitude: 81.5775,
        },
        description: '',
        experience: '7',
        language: 'Hindi',
    },
    {
        id: '3',
        name: 'Dr. Pradeep Mahajan',
        image: require('../../../assets/images/pradeep.jpeg'),
        speciality: 'Uro-Surgery',
        fee: '900',
        qualification: 'MBBS, MS – General Surgery, AFIH, Diploma in Urology',
        coordinate: {
            latitude: 25.5629,
            longitude: 85.0413,
        },
        description: '',
        experience: '15',
        language: 'English/Hindi',
    },
];