export default [
    {
        id: '0',
        name: 'Dr Kalpana Nagpal',
        image: require('../../../assets/images/kalpana.jpeg'),
        speciality: 'ENT',
        fee: '500',
        qualification: 'MBBS, MS (ENT), DNB (ENT)',
        coordinate: {
            latitude: 28.5672,
            longitude: 28.5672,
        },
        description: '',
        experience: '5',
        language: 'English/Hindi',
    },
    {
        id: '1',
        name: 'Dr. Avtar Singh Bath',
        image: require('../../../assets/images/avtar.jpeg'),
        speciality: 'Plastic & Cosmetic Surgery',
        fee: '700',
        qualification: 'MBBS MS (General Surgery) M Ch (Plastic Surgery)',
        coordinate: {
            latitude: 30.0818,
            longitude: 78.2888,
        },
        description: '',
        experience: '10',
        language: 'English',
    },
    {
        id: '2',
        name: 'Dr Ishwar Bohra',
        image: require('../../../assets/images/ishwar.jpeg'),
        speciality: 'Orthopaedics',
        fee: '600',
        qualification: 'MBBS, M.Ch. (Ortho), MS (Ortho) and MAMS',
        coordinate: {
            latitude: 21.2574,
            longitude: 81.5775,
        },
        description: '',
        experience: '7',
        language: 'Hindi',
    },
    {
        id: '3',
        name: 'Dr. Pradeep Mahajan',
        image: require('../../../assets/images/pradeep.jpeg'),
        speciality: 'Uro-Surgery',
        fee: '900',
        qualification: 'MBBS, MS – General Surgery, AFIH, Diploma in Urology',
        coordinate: {
            latitude: 25.5629,
            longitude: 85.0413,
        },
        description: '',
        experience: '15',
        language: 'English/Hindi',
    },
];