/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3fcdcb27-6d37-43d4-97b3-ece838d82ce8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_0k068w8zU",
    "aws_user_pools_web_client_id": "1l9vrvi8mvun923v3731dodiqq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gg2mnxpkjrclvp2asev7mnl3ty.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-y4emdnihtjdappupien5bdbhxm",
    "aws_cloud_logic_custom": [
        {
            "name": "StripeWebHook",
            "endpoint": "https://otjlwhu4a2.execute-api.us-east-2.amazonaws.com/stage",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
